[package]
name = "check_links"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.27.0"
reqwest = "0.12.3"
tokio = { version = "1.37.0", features = ["full"] }
url = "2.5.0"
